name: Build files

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get bootstrap
      run: curl https://gitlab.com/firefox8/firefox-bootstrap/-/raw/main/bootstrap.py -O
    - name: Run bootstrap
      run: python3 bootstrap.py
      
