name: CI

on:
    push:
        branches: [ main ]

workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

            steps:

            - name: Testing
              run: touch hello.py
